{{- $dot := . }}
{{- $Values := $dot.Values }}

{{- range $key, $val := (.Values.services_map | default dict) }}
{{ include "templating-deep-dive.v1.validators.service" $val }} {{/* or simply . as the root context becomes $val */}}
---
# The value of the .: {{ . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "templating-deep-dive.v1.fullname" $ }}-{{ $key }}-svc
  labels:
    {{- include "templating-deep-dive.v1.selectorLabels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  selector:
    {{- include "templating-deep-dive.v1.selectorLabels" $ | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ $Values.containerPorts.http }}
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ $Values.containerPorts.http }}
{{- end }}
